version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 111
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 111
      MARIADB_RANDOM_ROOT_PASSWORD: 111

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


