version: '3'

  #services:
  #  nginx:
  #    image: nginx
  #    restart: always
  #    deploy:
  #      replicas: 2

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=ROOT
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=root

    ports:
      - "5432:5432"
  pgadmin:
     image: dpage/pgadmin4
     environment:
        - PGADMIN_DEFAULT_EMAIL=odin@no.no
        - PGADMIN_DEFAULT_PASSWORD=1111
     ports:
        - 8081:80
     depends_on:
        - postgres
        
